# Generated by Django 2.2.14 on 2020-09-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('start_time', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('end_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=200)),
                ('tz', models.CharField(max_length=200)),
                ('activity_periods', models.ManyToManyField(default=1, to='task.activity')),
            ],
        ),
    ]
